### ISSUE TITLE
Services: Display the post title in align with its content

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#13]
![image](https://cloud.githubusercontent.com/assets/18568310/16257607/1be74f42-388c-11e6-9a31-96e806013f95.png)

**Comment by euveng** [comment]
Sorry, can you describe this issue in more detail?

**Comment by ricatitan** [comment]
I mean display the post title in line with the contents not  in line with the featured image. Anyway, it is already fixed.
Thanks
