### ISSUE TITLE
Services: There should be no single page.

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#14]
![image](https://cloud.githubusercontent.com/assets/18568310/16257694/a7095d9a-388c-11e6-8242-dca7e40e498d.png)

**Comment by euveng** [comment]
There has been a scope change, please see https://app2.magnetichq.com/Magnetic/OpenPopup.do?popup=ViewTask.do?taskId=48411117&main=Tasks.do
