### ISSUE TITLE
Admin: No FAQ custom post found.

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#20]
![image](https://cloud.githubusercontent.com/assets/18568310/16260081/4704e692-3898-11e6-8e26-ccec961c00aa.png)

**Comment by euveng** [comment]
The site was implemented using the new base template which uses ACF as the FAQ posts. 
The scope doc was created based on the old base template which uses CPT as the FAQ posts. This is a scope error.
