### ISSUE TITLE
News Page: Post content limits upto 5 lines

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#21]
![image](https://cloud.githubusercontent.com/assets/18568310/16258508/dc297da8-3890-11e6-83bd-9fe907b15b03.png)

**Comment by euveng** [comment]
Fixed.

**Comment by ricatitan** [comment]
Must limit upto 5 lines only

![image](https://cloud.githubusercontent.com/assets/18568310/16331316/0183efb0-3a22-11e6-8b46-89a4e92a8197.png)

**Comment by euveng** [comment]
Fixed.
