### ISSUE TITLE
Footer: Currently open page must be in active state.

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#30]
![image](https://cloud.githubusercontent.com/assets/18568310/16288910/19bf516e-3923-11e6-93da-75ea455bcc3d.png)

**Comment by euveng** [comment]
Please elaborate on this issue. Is there such a standard?

**Comment by ricatitan** [comment]
Please check the footer menu active state in the given design.
The menu should have an active state if the menu/page is currently open, the same with the header sub-menus.
Ensure that all active state is working properly. 
Thanks!

![image](https://cloud.githubusercontent.com/assets/18568310/16330991/93077de2-3a1f-11e6-92c2-26a4959e95f6.png)

![image](https://cloud.githubusercontent.com/assets/18568310/16331053/1bfd76c4-3a20-11e6-8d10-28e8d12f769c.png)

**Comment by euveng** [comment]
Ah yes, that's referring to the footer. Sure I'll fix this.

**Comment by euveng** [comment]
Fixed.
