### ISSUE TITLE
About Us: No margin in between images in edge browser 

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#31]
![image](https://cloud.githubusercontent.com/assets/18568310/16289002/1a84b35e-3924-11e6-973b-1d53abdff994.png)

**Comment by euveng** [comment]
Unable to reproduce issue. The margins look correct in edge and ie10. However there could have been a plugin that was bothering the page, which I have disabled. Please retest.

**Comment by ricatitan** [comment]
The issue can still be reproduce. There is still no margin.

See the screenshot below in other browsers.
![image](https://cloud.githubusercontent.com/assets/18568310/16330544/95ca5a02-3a1c-11e6-8ef9-d134fa90221f.png)

**Comment by euveng** [comment]
Fixed.
