### ISSUE TITLE
Testimonials: Make it fluid as long as the next row will not be affected

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#43]
![image](https://cloud.githubusercontent.com/assets/18568310/16293038/402f9252-3949-11e6-861b-0ac660fbdfd7.png)

**Comment by euveng** [comment]
I don't understand the issue, please provide clear description of the issue.

**Comment by ricatitan** [comment]
The issue is the space gap between title text and content. Regardless of how many lines the title of each testimonials, they should have they same space gap as long as the next row will not be destroy

![image](https://cloud.githubusercontent.com/assets/18568310/16367304/95ca5874-3c54-11e6-825b-7627437b4e97.png)

**Comment by euveng** [comment]
I would have to disagree with this. The title div heights are calculated to be equal across the row so that the testimonial content doesn't jump up and down across the row. What i have done is to reduce the title length to reduce the empty space.

**Comment by ricatitan** [comment]
Please see the screenshot below or refer to this site: http://interfreightlogistics.stage.titanweb.com.au/testimonials/

![image](https://cloud.githubusercontent.com/assets/18568310/16437999/45d3182a-3dde-11e6-92f2-93e4c17278d2.png)

**Comment by euveng** [comment]
Fixed.

**Comment by ricatitan** [comment]
Good job
