### ISSUE TITLE
Testimonial and News Page are lost

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#44]
![image](https://cloud.githubusercontent.com/assets/18568310/16293144/046cca2c-394a-11e6-8538-66316aac51fc.png)

**Comment by euveng** [comment]
I am 100% sure that I did not remove this. This probably happened during testing or content entry, I do not know. I have restored the menus.

**Comment by ricatitan** [comment]
I am also 100 % sure that i didn't also removed the pages mention.
