### ISSUE TITLE
Leadins: Incorrect font color when hovering

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#5]
![image](https://cloud.githubusercontent.com/assets/18568310/16256299/d120bfaa-3883-11e6-96ce-00933f1dcefb.png)

**Comment by euveng** [comment]
The colour that you picked through the inspector is upon hover, which has a opacity of 50% of the original colour at 100% opacity, which is #f7941e. This is not a bug, will not fix.
