### ISSUE TITLE
FAQ Page:  If either post title or content is not set, please hide the post

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#51]
![image](https://cloud.githubusercontent.com/assets/18568310/16369149/3f003a1c-3c69-11e6-8b6b-083452269300.png)
![image](https://cloud.githubusercontent.com/assets/18568310/16369163/52d9f8b6-3c69-11e6-8bf7-4f62706df224.png)

**Comment by euveng** [comment]
Fixed.
