### ISSUE TITLE
FAQ Page: Margin height must be 48px

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#58]
**As per design**
![image](https://cloud.githubusercontent.com/assets/18568310/16438355/98cc98c8-3de1-11e6-8845-fa57e45cc0bf.png)

![image](https://cloud.githubusercontent.com/assets/18568310/16438358/9c8ef2d0-3de1-11e6-993c-26e9407300c7.png)

**Comment by euveng** [comment]
This is a minor issue (10px) and should not have been flagged.
