### ISSUE TITLE
Homepage - Why choose us: Contents should also be required.

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#6]
![image](https://cloud.githubusercontent.com/assets/18568310/16256438/be4a5ef8-3884-11e6-917b-7a96392b0cce.png)

**Comment by euveng** [comment]
The current fields in the WP backend were entered by the CM/PM which are based on the final client copy. It happens that the copy does not have content under the heading. You may feel free to add your own content to test, but please remove it after testing. This is not a bug, will not fix.

**Comment by ricatitan** [comment]
What i mean is the contents should also be required as per the scope. Please see screenshot below
![image](https://cloud.githubusercontent.com/assets/18568310/16368034/6bf4ad9e-3c5c-11e6-834f-023bf8808cfb.png)

**Comment by euveng** [comment]
I understand that the content is part of the scope document, but in the client's actual application, there is no content. Therefore we should not force the client's hand to enter content that does not exist. This will not be fixed and I will mark this as change request.
