### ISSUE TITLE
Menu: Sub-menus must not be in active state

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#61]
![image](https://cloud.githubusercontent.com/assets/18568310/16438979/ba59e702-3de6-11e6-8088-696a6b136479.png)

It will be in active state when the sub-menu page is open. See screenshot below.
![image](https://cloud.githubusercontent.com/assets/18568310/16439004/0566fb68-3de7-11e6-80ce-8e0c93f5107b.png)

**Comment by euveng** [comment]
Fixed.
