### ISSUE TITLE
News Single: Please move down text starting from 606px - 560 px.  Please see the screenshot below 

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#66]
![image](https://cloud.githubusercontent.com/assets/18568310/16441930/eacfa934-3e00-11e6-84bb-e32a4f9c5a2a.png)

**Comment by euveng** [comment]
An inline image that is set to float left or right will automatically have text wrapping it at any width. This will not be fixed.

**Comment by ricatitan** [comment]
This is only a test data
