### ISSUE TITLE
Sidebar: Please add indication that the file is already attached.

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#68]
![image](https://cloud.githubusercontent.com/assets/18568310/16474413/2d3773d0-3ea9-11e6-9dba-e97e7b743c61.png)

**Comment by euveng** [comment]
Unfortunately this cannot be done due to the way the form has been styled, which has overridden most of the file upload styling attributes.

**Comment by ricatitan** [comment]
Here is the example why you successfully upload a file. See the screenshot below:

![image](https://cloud.githubusercontent.com/assets/18568310/16478648/7d283892-3ecd-11e6-8f61-2bd341942a4d.png)

**Comment by euveng** [comment]
The 'Choose file' button is not part of the design, which is why I hid it. If it is to be present after upload, it need to be present before upload as well.

**Comment by ricatitan** [comment]
How will I know that I've uploaded the correct attached file?

**Comment by euveng** [comment]
As I said: If it is to be present after upload, it will be present before upload as well. Can you confirm that this is ok?

**Comment by ricatitan** [comment]
Okay. Let see how it works then.

**Comment by euveng** [comment]
Ok, done, please check.

**Comment by ricatitan** [comment]
It is already achieved but the file name and its upload icon overlapped. 

![image](https://cloud.githubusercontent.com/assets/18568310/16481728/5925e608-3edf-11e6-8287-fab83f77a9dc.png)

**Comment by euveng** [comment]
Ok, try again.

**Comment by ricatitan** [comment]
It is now okay but when i submitted it UNSUCCESSFULLY, text overlapped. See screenshot below
![image](https://cloud.githubusercontent.com/assets/18568310/16481938/4576bf14-3ee0-11e6-9743-100c507c6bbb.png)

**Comment by euveng** [comment]
That's right. I've fixed it, please test again.

**Comment by ricatitan** [comment]
Hi @euveng , please assigned back to me the ticket, I'll gonna resolve it now. 
Thank you so much!
