### ISSUE TITLE
Homepage- Contact Us Section: Remove section field if section field is empty.

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#69]
![image](https://cloud.githubusercontent.com/assets/18568310/16475157/d7a700ba-3eae-11e6-992a-246141f31251.png)

**Comment by euveng** [comment]
This is a highly unlikely scenario - are you suggesting that the client will delete their address, phone, email address and contact form all at one time? I highly doubt it, so this is not a practical fix.
