### ISSUE TITLE
Homepage: Align email us and phone number at the center in 767px resolution and below. As you can notice it is not really align well in the center

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#73]
![image](https://cloud.githubusercontent.com/assets/18568310/16509209/0f3e131a-3f6d-11e6-98cc-d56fc705e495.png)

**Comment by euveng** [comment]
Fixed.

**Comment by ricatitan** [comment]
![image](https://cloud.githubusercontent.com/assets/18568310/16639555/200fad42-4423-11e6-9fcc-60d80865f1e4.png)

**Comment by euveng** [comment]
Fixed.
