### ISSUE TITLE
Leadins: Link should be required as per scope

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#76]
![image](https://cloud.githubusercontent.com/assets/18568310/16509955/7c62eb44-3f74-11e6-94b5-752eafed4cb4.png)

![image](https://cloud.githubusercontent.com/assets/18568310/16509961/8b9328ae-3f74-11e6-9263-5437babfabb2.png)

**Comment by euveng** [comment]
The new base framework allows for flexibility so the pagelink will not be a required field. Marking this as scope error.
