### ISSUE TITLE
About Us Page: Gallery are also hidden when featured image is hidden or empty.

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#77]
Gallery should not be hidden, the first gallery in the lists will be the one that will show in full width in replace with the featured image.

![image](https://cloud.githubusercontent.com/assets/18568310/16510884/b0a278f4-3f7c-11e6-8486-2e3981cf2507.png)

**Comment by euveng** [comment]
Unable to reproduce. Gallery still shows even if featured image is removed.

**Comment by ricatitan** [comment]
When I did the testing, galleries won't display when featured image is not set. I'll mark this as fixed since it is already fixed.
