### ISSUE TITLE
Sidebar: Either remove the "choose file icon" or remove its mouse on hover

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#80]
![image](https://cloud.githubusercontent.com/assets/18568310/16513073/3f100342-3f94-11e6-9904-71626f4e2c73.png)

**Comment by euveng** [comment]
Why?

**Comment by ricatitan** [comment]
Because it will be redundant. There would be two options in choosing the file, the "choose file" icon in the left part and the "icon" in the right. I suggest, you will remove the icon or stay as it is but remove its mouse on hover since it is not functioning anyway.

![image](https://cloud.githubusercontent.com/assets/18568310/16639720/cd7e76ec-4424-11e6-8a1d-9809e932ca42.png)

**Comment by euveng** [comment]
Removed.
