### ISSUE TITLE
General: Incorrect margin from the page contents to the footer

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#83]
**examples:** 

**testimonial page:**
![image](https://cloud.githubusercontent.com/assets/18568310/16513450/7706b59a-3f97-11e6-99b7-9fb8f18e0105.png)
**faq page:**
![image](https://cloud.githubusercontent.com/assets/18568310/16513734/8a83ba30-3f99-11e6-8d06-b8bbfba2c581.png)
**about us**
![image](https://cloud.githubusercontent.com/assets/18568310/16513838/6072e698-3f9a-11e6-915c-af2d2c2e4d0a.png)

**contact Us:**

![image](https://cloud.githubusercontent.com/assets/18568310/16513878/b3ae752a-3f9a-11e6-80a5-c539d3f11513.png)

**Comment by euveng** [comment]
Fixed.

**Comment by ricatitan** [comment]
This is not a major issue but please do fix it.
Thanks 

In testimonial page.

![image](https://cloud.githubusercontent.com/assets/18568310/16639950/e108adde-4426-11e6-8c25-301ad51a3a9c.png)

**Comment by euveng** [comment]
Fixed.
