### ISSUE TITLE
Homepage - why choose us: Numbers are not align vertical at the middle.

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#86]
![image](https://cloud.githubusercontent.com/assets/18568310/16513639/dedd82b0-3f98-11e6-9dd9-57d3fce6ed23.png)

**Comment by euveng** [comment]
Please refer to the design, it is not supposed to be vertically middle-aligned.

**Comment by euveng** [comment]
Fixed.
