### ISSUE TITLE
Banner: Images are blurred.

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#88]
![image](https://cloud.githubusercontent.com/assets/18568310/16640841/1210ce46-442e-11e6-847c-f53e5dd76a29.png)

**Comment by euveng** [comment]
If you upload an image with low resolution, you will see an image with low resolution. Please try with a high-res image.

**Comment by ricatitan** [comment]
Image is pixelated

![Uploading image.png…]()
