### ISSUE TITLE
Banner: Banner image does not have same height during responsive testing

### ISSUE THREAD

**Issue by ricatitan** [titan-cebu/Glazing-Vision#89]
![image](https://cloud.githubusercontent.com/assets/18568310/16643790/563a272c-444a-11e6-9927-fbc77d42486c.png)

**Comment by euveng** [comment]
Unable to reproduce even after retesting with images of different dimensions.

**Comment by ricatitan** [comment]
Steps to reproduce

1. Resize your browser or do the responsive checking. (i.e. in 767px resolution)
2. Navigate the banners

Notice: Image doesn't have the same height. See screenshot

![image](https://cloud.githubusercontent.com/assets/18568310/16674660/f3610e06-44ec-11e6-916a-d1673e32b239.png)

![image](https://cloud.githubusercontent.com/assets/18568310/16674685/6532d3a2-44ed-11e6-9722-011de887381d.png)
